### ISSUE TITLE
Creado archivos

### ISSUE THREAD

**Issue by albalvave** [LiChuan1234/trabajo01grupotd2023#4]
He creado dos archivos Rmardown, uno para poner los enunciados y otro para los enunciados con las soluciones. Pero no se si os sale o no. Por que llevo varios intentos. Yo he hecho Rmarkdown por mas comodo el escribir los enunciados, si preferis otro podeis cambiarlo

**Comment by LiChuan1234** [comment]
A mí sí me sale. No habéis puesto vuestros problemas todavía no? Para saber si deberían salirme o no

**Comment by albalvave** [comment]
Yo aun no lo he puesto, mañana por la mañana los añado

**Comment by wintershine23** [comment]
Yo lo acabo de subir. Necesito que alguna cree el archivo pdf puesto que a mi me esta dando problemas y me diga si se visualiza correctamente las formulas que he puesto. En caso de que no, decirme una manera fácil y rápida de crear una tabla en R.

**Comment by albalvave** [comment]
He intentado crear el pdf, pero tengo un problema con la version de latex. Mañana lo intentare solucionar a ver si puedo crear el documento.

**Comment by wintershine23** [comment]
Ya he creado el pdf del enunciado, voy a crear el otro si puedo. La culpa de que no saliera era mía que he intentado que funciona con código latex y R no ha estado de acuerdo conmigo.

**Comment by LiChuan1234** [comment]
Es que no entiendo tu forma de poner la tabla, por qué no has puesto lo del kable?

**Comment by wintershine23** [comment]
Porque soy muy bruta y quiero sacarle 10 patas al gato. Pero bueno ya queda todo solucionado. He subido lo otro también con su pdf. Yo me la lio yo lo soluciono.

**Comment by wintershine23** [comment]
Porque soy muy bruta y quiero sacarle 10 patas al gato. Pero bueno ya queda todo solucionado. He subido lo otro también con su pdf. Yo me la lio yo lo soluciono.

**Comment by LiChuan1234** [comment]
Vale, gracias :) A mí es que no me deja, lo estuve intentando ayer y esta tarde pero es por un problema que tengo con el latex y creo que llevará tiempo arreglarlo :(
