### ISSUE TITLE
crear pdf

### ISSUE THREAD

**Issue by wintershine23** [LiChuan1234/trabajo01grupotd2023#5]
Alguna puede crear el pdf de los archivos Rmarkdown que a mi no me funciona.

**Comment by LiChuan1234** [comment]
Ahora mismo iba a decirte que no me funciona
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
A new version of TeX Live has been released. If you need to install or update any LaTeX packages, you have to upgrade TinyTeX with tinytex::reinstall_tinytex(repository = "illinois").
! Undefined control sequence.
l.132 \multirow

**Comment by albalvave** [comment]
A mi tampoco me deja, de ninguna forma

**Comment by wintershine23** [comment]
Solucionado
