### ISSUE TITLE
Archivo ReadMe

### ISSUE THREAD

**Issue by albalvave** [LiChuan1234/trabajo01grupotd2023#7]
Acordaros de poner vuestro nombre en el archivo, que lo acabo de ver en el enunciado del trabajo al revisarlo.

Un fichero README.md (markdown sin código R) que incluya una breve descripción delcontenido del repositorio, nombres de los alumnos y cómo se realizó la organización.

**Comment by LiChuan1234** [comment]
Ahora mismo no puedo pero esta tarde creo el archivo

**Comment by LiChuan1234** [comment]
He completado el Readme, miradlo a ver si os parece bien

**Comment by albalvave** [comment]
Esta perfecto

**Comment by wintershine23** [comment]
Esta perfecto.
